### ISSUE TITLE
Dragging files into Firefox doesn't work. Works in Chromium

### ISSUE THREAD

**Issue by isf63** [lxqt/xdg-desktop-portal-lxqt#44]
Set `widget.use-xdg-desktop-portal.file-picker` and `widget.use-xdg-desktop-portal.mime-handler` =1 in Firefox.

Chromium accept DnD files, but the cursor when dragging over Firefox changes to "invalid".

**Comment by tsujan** [comment]
Here, it works for both. I'm in LXQt+kwin_wayland, but it shouldn't make a difference as long as `xdg-desktop-portal-lxqt ` is concerned — if it does, the issue should be somewhere else.

**Comment by isf63** [comment]
For me it's working in Wayland with Kwin (the only Wayland compositor I have installed). On X11 with both Xfwm4 and Kwin it doesn't work.

**Comment by tsujan** [comment]
Can you drop files into Firefox from pcmanfm-qt under X11?

**Comment by isf63** [comment]
No, that is what I meant initially. Both Desktop and Pcmanfm-qt windows are blocked - the mouse cursor turns into the "Invalid" icon.

**Comment by tsujan** [comment]
Then it can't be related to `xdg-desktop-portal-lxqt`. Most probably, it's a problem in Firefox or a setting in it.

**Comment by tsujan** [comment]
This is how libfm-qt works:

https://github.com/lxqt/libfm-qt/blob/330c6137dbeea93c2b9bc92a119933c49f399433/src/foldermodel.cpp#L512-L550

As it's clear from the code, it doesn't make any exception for X11 or Wayland.

My wild guess is that, since some version, Firefox doesn't recognize local paths in its X11 DND. libfm-qt prefers local paths if they exist (the reason is explained in the code).
